### ISSUE TITLE
The requested file could not be read...

### ISSUE THREAD

**Issue by blixel2** [Kimbatt/torrent-creator#11]
I'm trying to create a torrent for 4 ISOs. Each ISO is ~8GB. When I click "Create Torrent", I keep getting this message:
Failed to read file: [filename].iso. Reason: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired. (NotReadableError)

I attempted to break the files up into 700MB chunks using WinRAR, but I had the same problem. I then attempted to break the files up into 100MB chunks (also using WinRAR), but the problem persists.

I would appreciate help resolving the issue. Thanks.

**Comment by Kimbatt** [comment]
Hi,
I pushed a fix that should resolve this issue. Could you check it and see if it works now?

**Comment by blixel2** [comment]
Wow, thanks for the fast response. Works perfectly now!
