### ISSUE TITLE
rtorrent will not load files created with this tool

### ISSUE THREAD

**Issue by aland** [Kimbatt/torrent-creator#3]
Torrents created by tool have issues with rtorrent, preventing the file from being loaded.
Some users report an "Error: null" message displayed, but for me it says the file was loaded - although it never appears in the list.

**Comment by Kimbatt** [comment]
Please check if this issue still occurs.
The latest commit (ee40130) fixed an issue with torrents created from folders having 0 size.

**Comment by aland** [comment]
works for me
